# Generated by Django 5.0 on 2023-12-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databarang',
            name='tanggal_ditambah',
            field=models.DateField(),
        ),
    ]
